tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "iveney/mocha"
brew "arp-scan"
brew "ascii"
brew "bash"
brew "bat"
brew "brew-cask-completion"
brew "coreutils"
brew "cask"
brew "duf"
brew "exa"
brew "ffmpeg"
brew "git"
brew "gnu-sed"
brew "gnu-typist"
brew "gnupg"
brew "grex"
brew "htop"
brew "imagemagick"
brew "ipcalc"
brew "ipython"
brew "mas"
brew "masscan"
brew "ncdu"
brew "nmap"
brew "procs"
brew "python-tk@3.9"
brew "rename"
brew "ripgrep"
brew "rsync"
brew "sipcalc"
brew "syncthing"
brew "tealdeer"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
brew "iveney/mocha/realpath", link: false
cask "drawio"
cask "firefox"
cask "font-fira-code"
cask "font-fira-mono-for-powerline"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "font-material-icons"
cask "ghost-browser"
cask "iterm2"
cask "macfuse"
cask "nextcloud"
cask "notion"
cask "silentknight"
cask "suspicious-package"
cask "visual-studio-code"
cask "vlc"
mas "Apple Configurator 2", id: 1037126344
mas "Bear", id: 1091189122
mas "Bitwarden", id: 1352778147
mas "Kindle", id: 405399194
mas "Magnet", id: 441258766
mas "Microsoft To Do", id: 1274495053
mas "Python Recipes", id: 1180825853
mas "Slack", id: 803453959
mas "WireGuard", id: 1451685025
