tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "iveney/mocha"
brew "antigen"
brew "bats"
brew "libffi"
brew "openssl"
brew "cairo"
brew "cmatrix"
brew "docker"
brew "docker-compose"
brew "docker-machine"
brew "fasd"
brew "flac"
brew "fribidi"
brew "gmp"
brew "libevent"
brew "libunistring"
brew "libtasn1"
brew "nettle"
brew "graphite2"
brew "harfbuzz"
brew "libvorbis"
brew "ffmpeg"
brew "pcre2"
brew "git"
brew "gnupg"
brew "irssi"
brew "libav"
brew "libtool"
brew "mas"
brew "ncdu"
brew "ncurses"
brew "nmap"
brew "node"
brew "openldap"
brew "pstree"
brew "rename"
brew "tldr"
brew "tree"
brew "weechat"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
cask "adoptopenjdk"
cask "brave-browser"
cask "chromium"
cask "mullvadvpn"
cask "netbeans"
cask "powershell"
cask "profilecreator"
cask "sabnzbd"
cask "suspicious-package"
cask "telegram"
cask "the-unarchiver"
cask "vagrant"
cask "virtualbox"
mas "Apple Configurator 2", id: 1037126344
mas "Bear", id: 1091189122
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
