tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "iveney/mocha"
brew "openssl"
brew "cmatrix"
brew "ffmpeg"
brew "pcre2"
brew "git"
brew "gnupg"
brew "mas"
brew "htop"
brew "rename"
brew "tldr"
brew "tree"
brew "youtube-dl"
brew "zsh"
cask "chromium"
cask "powershell"
cask "profilecreator"
cask "sabnzbd"
cask "suspicious-package"
cask "telegram"
cask "the-unarchiver"
cask "virtualbox"
mas "Apple Configurator 2", id: 1037126344
mas "Bear", id: 1091189122
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Pocket", id: 568494494
